tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed": "#c9e6ff",
                "on-surface": "#e5e1e4",
                "surface-container-highest": "#353437",
                "on-primary-fixed-variant": "#2f2ebe",
                "on-tertiary": "#00344d",
                "secondary-fixed": "#f0dbff",
                "on-secondary-container": "#d6a9ff",
                "on-secondary-fixed-variant": "#6900b3",
                "error-container": "#93000a",
                "outline-variant": "#464554",
                "on-secondary-fixed": "#2c0051",
                "on-tertiary-fixed": "#001e2f",
                "inverse-surface": "#e5e1e4",
                "surface-dim": "#131315",
                "surface-container-low": "#1c1b1d",
                "tertiary": "#89ceff",
                "primary-container": "#8083ff",
                "on-surface-variant": "#c7c4d7",
                "on-secondary": "#490080",
                "surface-container-high": "#2a2a2c",
                "primary-fixed-dim": "#c0c1ff",
                "on-error-container": "#ffdad6",
                "secondary-container": "#6f00be",
                "secondary": "#ddb7ff",
                "on-primary-container": "#0d0096",
                "surface-bright": "#39393b",
                "on-tertiary-fixed-variant": "#004c6e",
                "surface-tint": "#c0c1ff",
                "on-background": "#e5e1e4",
                "surface": "#131315",
                "on-primary-fixed": "#07006c",
                "surface-container-lowest": "#0e0e10",
                "tertiary-container": "#009ada",
                "error": "#ffb4ab",
                "secondary-fixed-dim": "#ddb7ff",
                "surface-variant": "#353437",
                "inverse-primary": "#494bd6",
                "background": "#131315",
                "on-primary": "#1000a9",
                "primary-fixed": "#e1e0ff",
                "primary": "#c0c1ff",
                "outline": "#908fa0",
                "tertiary-fixed-dim": "#89ceff",
                "inverse-on-surface": "#313032",
                "surface-container": "#201f22",
                "on-error": "#690005",
                "on-tertiary-container": "#002d43"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "container-max": "1440px",
                "stack-xs": "4px",
                "stack-md": "16px",
                "gutter": "16px",
                "stack-sm": "8px",
                "stack-lg": "32px",
                "margin": "24px",
                "base": "4px"
            },
            "fontFamily": {
                "body-lg": ["Geist"],
                "headline-md": ["Geist"],
                "headline-lg": ["Geist"],
                "label-caps": ["JetBrains Mono"],
                "code-sm": ["JetBrains Mono"],
                "body-md": ["Geist"],
                "code-md": ["JetBrains Mono"]
            },
            "fontSize": {
                "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-caps": ["11px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "code-sm": ["12px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
                "body-md": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
                "code-md": ["14px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
            }
        },
    },
}